# Identificação do Sistema
spring.application.name=tavern-hub

# Banco de Dados H2 (Em memória, roda rápido sem precisar instalar nada no Ubuntu)
spring.datasource.url=jdbc:h2:mem:taverndb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Habilita o painel visual do banco no navegador (localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.settings.web-allow-others=false

# Logs do Hibernate (Mostra no terminal os SQLs que seriam gerados pelo ORM)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Sincronização Automática: Cria as tabelas baseado nas classes Java que vamos fazer
spring.jpa.hibernate.ddl-auto=update

# Internacionalização: Forçando a API a usar o fuso de Brasília (UTC-3)
spring.jackson.time-zone=America/Sao_Paulo